image: node:latest

stages:
  - test
  - build-frontend
  - build-client
  - deploy

cache:
  paths:
    - frontend/node_modules

test-frontend:
  stage: test
  script:
    - cd frontend
    - yarn install
    - yarn test

test-client:
  stage: test
  script:
    - cd client
    - apt-get -yq update
    - apt-get -yq install python3-pip
    - pip3 install --user bitarray
    - pip3 install --user https://github.com/rogerbinns/apsw/releases/download/3.30.1-r1/apsw-3.30.1-r1.zip \
        --global-option=fetch --global-option=--version --global-option=3.30.1 --global-option=--all \
        --global-option=build --global-option=--enable-all-extensions
    - python3 src/_unit_tests.py

systest-client:
  stage: test
  script:
    - apt-get -yq update
    - apt-get -yq install python3-pip
    - pip3 install --user bitarray flask flask-cors flask_swagger_ui
    - pip3 install --upgrade --user idna
    - git clone https://github.com/martmaemees/aprs.git
    - cd aprs
    - python3 setup.py install
    - pip3 install --user https://github.com/rogerbinns/apsw/releases/download/3.30.1-r1/apsw-3.30.1-r1.zip \
        --global-option=fetch --global-option=--version --global-option=3.30.1 --global-option=--all \
        --global-option=build --global-option=--enable-all-extensions
    - cd ../client
    - bash sys_test.sh

build-frontend:
  stage: build-frontend
  script:
    - cd frontend
    - yarn install
    - yarn build:prod
  artifacts:
    paths:
      - frontend/app/dist
    name: "telemetry-frontend-$CI_COMMIT_REF_SLUG"
    expire_in: 5 days

build-client:
  stage: build-client
  script:
    - cd client
    - bash build.sh
  artifacts:
    paths:
      - dist
    name: "telemetry-decoder-client-$CI_COMMIT_REF_SLUG"
    expire_in: 3 weeks

deploy-client:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - cd dist
    - ssh -l deploy "$TEST_ENV_IP" "sudo /bin/systemctl stop estcube-client"
    - ssh -l deploy "$TEST_ENV_IP" "rm -rf /srv/client/*"
    - scp -r * deploy@"$TEST_ENV_IP":/srv/client
    - ssh -l deploy "$TEST_ENV_IP" "sudo /bin/systemctl start estcube-client"
  only:
    - master