image: node:latest

cache:
  paths:
    - frontend/node_modules

test-frontend:
  stage: test
  script:
    - cd frontend
    - yarn install
    - yarn test

build-frontend:
  stage: build
  script:
    - cd frontend
    - yarn install
    - yarn build:prod
  artifacts:
    paths:
      - frontend/app/dist/
    name: "telemetry-frontend-$CI_COMMIT_REF_SLUG"