image: node:latest

stages:
  - test
  - build-frontend
  - build-client
  - deploy

cache:
  paths:
    - frontend/node_modules

test-frontend:
  stage: test
  script:
    - cd frontend
    - yarn install
    - yarn test

test-client:
  image: martmaemees/ec2-telemetry:0.1.2-client
  stage: test
  script:
    - cd client
    - python3 src/_unit_tests.py

systest-client:
  image: martmaemees/ec2-telemetry:0.1.2-client
  stage: test
  script:
    - cd client
    - sh sys_test.sh

build-frontend:
  stage: build-frontend
  script:
    - cd frontend
    - yarn install
    - yarn build:prod
  artifacts:
    paths:
      - frontend/app/dist
    name: "telemetry-frontend-$CI_COMMIT_REF_SLUG"
    expire_in: 5 days

build-client:
  stage: build-client
  script:
    - cd client
    - sh build.sh
  artifacts:
    paths:
      - dist
    name: "telemetry-decoder-client-$CI_COMMIT_REF_SLUG"
    expire_in: 3 weeks

deploy-client:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - cd dist
    - ssh -l deploy "$TEST_ENV_IP" "sudo /bin/systemctl stop estcube-client"
    - ssh -l deploy "$TEST_ENV_IP" "rm -rf /srv/client/*"
    - scp -r * deploy@"$TEST_ENV_IP":/srv/client
    - ssh -l deploy "$TEST_ENV_IP" "chown -R :www-data /srv/client/*"
    - ssh -l deploy "$TEST_ENV_IP" "chmod -R g+w /srv/client/*"
    - ssh -l deploy "$TEST_ENV_IP" "sudo /bin/systemctl start estcube-client"
  only:
    - master
