swagger: "2.0"
info:
  description: "This is API description for Estcube 2 Telemetry client API. API is built using Flask and is not RESTful."
  version: "1.0.0"
  title: "Estcube 2 Telemetry API"
basePath: "/api"
paths:
  /telemetry/packets:
    get:
      tags:
        - "telemetry"
      summary: "Saved telemetry packets."
      description: "Returns the saved telemetry packets."
      produces:
        - "application/json"
      responses:
        200:
          schema:
            $ref: "#/definitions/TelemetryPackets"
  /telemetry/configuration:
    get:
      tags:
        - "telemetry"
      summary: "Configuration of the telemetry fields."
      description: "Returns the configuration of the telemetry fields."
      produces:
        - "application/json"
      responses:
        200:
          schema:
            $ref: "#/definitions/TelemetryConf"



  /conf:
    post:
      tags:
      - "conf"
      summary: "Updates configuration."
      description: "Updates configuration in client."
      operationId: "updateConf"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Configuration object which will update clients configuration"
        required: true
        schema:
          $ref: "#/definitions/ConfPost"
      responses:
        200:
          description: "successful operation"
        400:
          description: "error"
    get:
      tags:
      - "conf"
      summary: "Gets some configuration!"
      description: "Gets configuration."
      operationId: "getConf"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Conf"
  /conf/full:
    get:
      tags:
      - "conf"
      summary: "Gets some all decked out configuration!"
      description: "Gets full configuration."
      operationId: "getConfFull"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ConfFull"
  /conf/constraints:
    get:
      tags:
      - "conf"
      summary: "Gets some configuration with constraints!"
      description: "Gets configuration with constraints."
      operationId: "getConfConstraints"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ConfConstraints"
  /data:
    get:
      tags:
      - "data"
      summary: "Get some data from local DB."
      description: "Gets some data."
      operationId: "getData"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Data"

definitions:
  TelemetryPackets:
    type: "object"
    properties:
      packets:
        type: "array"
        items:
          $ref: "#/definitions/TelemetryPacket"

  TelemetryPacket:
    type: "object"
    properties:
      id:
        type: "integer"
        example: 1
      packet_timestamp:
        type: "string"
        example: "2019-11-21T21:43:58.977179"
      receive_timestamp:
        type: "string"
        example: "2019-11-21T21:55:58.977179"
      fields:
        type: "object"


  TelemetryConf:
    type: "object"
    properties:
      prefix:
        type: "string"
        example: "data.payload"
      msgTimestamp:
        type: "object"
        properties:
          id:
            type: "string"
            example: "timestamp"
          type:
            type: "string"
            example: "unix_timestamp"
      fields:
        type: "array"
        items:
          $ref: "#/definitions/TelemetryConfField"
      graphs:
        type: "array"
        items:
          $ref: "#/definitions/TelemetryConfGraph"

  TelemetryConfField:
    type: "object"
    properties:
      id:
        type: "string"
        example: "main_bus_volt"
      type:
        type: "string"
        example: "int"
      unit:
        type: "string"
        example: "Volts"
      label:
        type: "string"
        example: "Main bus voltage"

  TelemetryConfGraph:
    type: "object"
    properties:
      xAxis:
        type: "string"
        example: "timestamp"
      yAxis:
        type: "array"
        items:
          type: "string"
        example:
          - "bat_a_volt"
          - "bat_b_volt"
          - "bat_c_volt"
      title:
        type: "string"
        example: "Battery voltages"



  ClientConfObject:
    type: "object"
    properties:
      database:
        type: "string"
      frontend-port:
        type: "string"
      static-files-path:
        type: "string"

  ClientConfObjectFull:
    type: "object"
    properties:
      database:
        type: "object"
        properties:
          description:
            type: "string"
          label:
            type: "string"
          requiresRestart:
            type: "boolean"
          type:
            type: "string"
          value:
            type: "string"
      frontend-port:
        type: "object"
        properties:
          description:
            type: "string"
          label:
            type: "string"
          requiresRestart:
            type: "boolean"
          type:
            type: "string"
          value:
            type: "string"
      static-files-path:
        type: "object"
        properties:
          description:
            type: "string"
          label:
            type: "string"
          requiresRestart:
            type: "boolean"
          type:
            type: "string"
          value:
            type: "string"

  ClientConfObjectConstraints:
    type: "object"
    properties:
      database:
        type: "object"
        properties:
          description:
            type: "string"
          label:
            type: "string"
          requiresRestart:
            type: "boolean"
          type:
            type: "string"
      frontend-port:
        type: "object"
        properties:
          description:
            type: "string"
          label:
            type: "string"
          requiresRestart:
            type: "boolean"
          type:
            type: "string"
      static-files-path:
        type: "object"
        properties:
          description:
            type: "string"
          label:
            type: "string"
          requiresRestart:
            type: "boolean"
          type:
            type: "string"



  MCSConfObject:
    type: "object"
    properties:
      latitude:
        type: "string"
      longitude:
        type: "string"
      mcs-relay-url:
        type: "string"
      noradID:
        type: "string"
      receiver-callsign:
        type: "string"
      relay-enabled:
        type: "boolean"

  MCSConfObjectFull:
    type: "object"
    properties:
      latitude:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          value:
            type: "integer"
      longitude:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          value:
            type: "integer"
      mcs-relay-url:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          value:
            type: "string"
      norad-id:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          value:
            type: "integer"
      receiver-callsign:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          value:
            type: "string"
      relay-enabled:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          value:
            type: "boolean"

  MCSConfObjectConstraints:
    type: "object"
    properties:
      latitude:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
      longitude:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
      mcs-relay-url:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
      norad-id:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
      receiver-callsign:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
      relay-enabled:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"


  TNCConfObject:
    type: "object"
    properties:
      connection-retry-time:
        type: "string"
      max-connection-attempts:
        type: "string"
      tnc-connection-type:
        type: "string"
      tnc-device:
        type: "string"
      tnc-ip:
        type: "string"
      tnc-port:
        type: "string"
      tnc-protocol-type:
        type: "string"

  TNCConfObjectFull:
    type: "object"
    properties:
      connection-retry-time:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          value:
            type: "integer"
          requiresRestart:
            type: "boolean"
      max-connection-attempts:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          value:
            type: "integer"
          requiresRestart:
            type: "boolean"
      tnc-connection-type:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          value:
            type: "string"
          requiresRestart:
            type: "boolean"
          options:
            type: "array"
            items:
              type: "string"
            example: ["RS232", "TCP/IP"]
      tnc-device:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          value:
            type: "string"
          requiresRestart:
            type: "boolean"
      tnc-ip:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          value:
            type: "string"
          requiresRestart:
            type: "boolean"
      tnc-protocol-type:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          value:
            type: "string"
          requiresRestart:
            type: "boolean"
          options:
            type: "array"
            items:
              type: "string"
            example: ["KISS"]
          disabledOptions:
            type: "array"
            items:
              type: "string"
            example: ["AGW"]

  TNCConfObjectConstraints:
    type: "object"
    properties:
      connection-retry-time:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          requiresRestart:
            type: "boolean"
      max-connection-attempts:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          requiresRestart:
            type: "boolean"
      tnc-connection-type:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          requiresRestart:
            type: "boolean"
          options:
            type: "array"
            items:
              type: "string"
            example: ["RS232", "TCP/IP"]
      tnc-device:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          requiresRestart:
            type: "boolean"
      tnc-ip:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          requiresRestart:
            type: "boolean"
      tnc-protocol-type:
        type: "object"
        properties:
          label:
            type: "string"
          type:
            type: "string"
          requiresRestart:
            type: "boolean"
          options:
            type: "array"
            items:
              type: "string"
            example: ["KISS"]
          disabledOptions:
            type: "array"
            items:
              type: "string"
            example: ["AGW"]
<<<<<<< HEAD

=======
  PostBody:
    type: "object"
    properties:
      "param name1":
        example: "param value 1"
      "param name2":
        example: "param value 2"
>>>>>>> master
  ConfConstraints:
    type: "object"
    properties:
      Client:
        $ref: "#/definitions/ClientConfObjectConstraints"
      "Mission Control":
        $ref: "#/definitions/MCSConfObjectConstraints"
<<<<<<< HEAD
      TNCInterface:
        $ref: "#/definitions/TNCConfObjectConstraints"
=======
      "TNC Interface":
        $ref: "#/definitions/TNCConfObjectConstraints"  
>>>>>>> master
    xml:
      name: "ConfFull"
  ConfFull:
    type: "object"
    properties:
      Client:
        $ref: "#/definitions/ClientConfObjectFull"
      "Mission Control":
        $ref: "#/definitions/MCSConfObjectFull"
<<<<<<< HEAD
      TNCInterface:
        $ref: "#/definitions/TNCConfObjectFull"
=======
      "TNC Interface":
        $ref: "#/definitions/TNCConfObjectFull"  
>>>>>>> master
    xml:
      name: "ConfFull"
  Conf:
    type: "object"
    properties:
      Client:
        $ref: "#/definitions/ClientConfObject"
      "Mission Control":
        $ref: "#/definitions/MCSConfObject"
<<<<<<< HEAD
      TNCInterface:
        $ref: "#/definitions/TNCConfObject"
    xml:
      name: "Conf"
=======
      "TNC Interface":
        $ref: "#/definitions/TNCConfObject"  
    xml:
      name: "Conf"
  ConfPost:
    type: "object"
    properties:
      Client:
        $ref: "#/definitions/PostBody"
      "Mission Control":
        $ref: "#/definitions/PostBody"
      "TNC Interface":
        $ref: "#/definitions/PostBody"
>>>>>>> master
  Data:
    type: "object"
    properties:
      data:
        type: "object"
        properties:
          some-dats:
            type: "string"
            example: "datdatdat"
      timestamp:
        type: "string"
    xml:
      name: "Data"